### ISSUE TITLE
What is 'label' for?

### ISSUE THREAD

**Issue by andrabujan** [CATH-summer-2018/SFAM-naming#5]
Hi,

I was wondering if we should write anything in the 'Label' section, next to the superfamily name box when editing?

Thanks,
Andra

**Comment by ilsenatorov** [comment]
I talked to Ian about it, he said that it will be a unique identifier that will be used alongside usual CATH identifier (1.10.100.1000) but will be a bit more meaningful and will be somehow derived from the actual name. For now we can ignore it.
